"""update models

Revision ID: 037659c43fb1
Revises: 9b057612d9dc
Create Date: 2025-06-24 00:34:09.841060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037659c43fb1'
down_revision: Union[str, Sequence[str], None] = '9b057612d9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_prices', 'open',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=6),
               existing_nullable=True)
    op.alter_column('daily_prices', 'high',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=6),
               existing_nullable=True)
    op.alter_column('daily_prices', 'low',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=6),
               existing_nullable=True)
    op.alter_column('daily_prices', 'close',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=6),
               existing_nullable=True)
    op.alter_column('daily_prices', 'adj_close_backward',
               existing_type=sa.NUMERIC(precision=19, scale=4),
               type_=sa.Numeric(precision=19, scale=6),
               existing_nullable=True)
    op.alter_column('daily_prices', 'adj_factor',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               type_=sa.Numeric(precision=20, scale=12),
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_prices', 'adj_factor',
               existing_type=sa.Numeric(precision=20, scale=12),
               type_=sa.NUMERIC(precision=20, scale=10),
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('daily_prices', 'adj_close_backward',
               existing_type=sa.Numeric(precision=19, scale=6),
               type_=sa.NUMERIC(precision=19, scale=4),
               existing_nullable=True)
    op.alter_column('daily_prices', 'close',
               existing_type=sa.Numeric(precision=19, scale=6),
               type_=sa.NUMERIC(precision=19, scale=4),
               existing_nullable=True)
    op.alter_column('daily_prices', 'low',
               existing_type=sa.Numeric(precision=19, scale=6),
               type_=sa.NUMERIC(precision=19, scale=4),
               existing_nullable=True)
    op.alter_column('daily_prices', 'high',
               existing_type=sa.Numeric(precision=19, scale=6),
               type_=sa.NUMERIC(precision=19, scale=4),
               existing_nullable=True)
    op.alter_column('daily_prices', 'open',
               existing_type=sa.Numeric(precision=19, scale=6),
               type_=sa.NUMERIC(precision=19, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
