"""Update DailyPrice model

Revision ID: 15ca85d367a0
Revises: 8d78aebe9d02
Create Date: 2025-06-27 17:03:57.612931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ca85d367a0'
down_revision: Union[str, Sequence[str], None] = '8d78aebe9d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('turnover', sa.Numeric(precision=25, scale=4), nullable=True, comment='成交额'))
    op.add_column('daily_prices', sa.Column('vwap', sa.Numeric(precision=19, scale=6), nullable=True, comment='成交量加权平均价 (VWAP), 可作为平均价'))
    op.add_column('daily_prices', sa.Column('turnover_rate', sa.Numeric(precision=10, scale=6), nullable=True, comment='换手率 (需要总股本数据计算)'))
    op.alter_column('daily_prices', 'adj_factor',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.drop_column('daily_prices', 'cal_event_factor')
    op.drop_column('daily_prices', 'adj_close')
    op.drop_column('daily_prices', 'event_factor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('event_factor', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=False))
    op.add_column('daily_prices', sa.Column('adj_close', sa.NUMERIC(precision=19, scale=6), autoincrement=False, nullable=True))
    op.add_column('daily_prices', sa.Column('cal_event_factor', sa.NUMERIC(precision=20, scale=6), server_default=sa.text('1.0'), autoincrement=False, nullable=False))
    op.alter_column('daily_prices', 'adj_factor',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.drop_column('daily_prices', 'turnover_rate')
    op.drop_column('daily_prices', 'vwap')
    op.drop_column('daily_prices', 'turnover')
    # ### end Alembic commands ###
