"""Add info_last_updated to Security model

Revision ID: 3bf1dd222fb8
Revises: 8c666c3093ce
Create Date: 2025-06-25 14:39:59.307227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf1dd222fb8'
down_revision: Union[str, Sequence[str], None] = '8c666c3093ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('info_last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securities', 'info_last_updated')
    # ### end Alembic commands ###
