"""Update models

Revision ID: 4643f121fe66
Revises: eb8dcc66f0c6
Create Date: 2025-06-26 15:22:43.447491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4643f121fe66'
down_revision: Union[str, Sequence[str], None] = 'eb8dcc66f0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('amount', sa.Numeric(precision=25, scale=6), nullable=True, comment='成交额'))
    op.add_column('daily_prices', sa.Column('avg_price', sa.Numeric(precision=19, scale=6), nullable=True, comment='平均价 (成交额/成交量)'))
    op.alter_column('daily_prices', 'volume',
               existing_type=sa.BIGINT(),
               comment='成交量（股）',
               existing_nullable=True)
    op.alter_column('daily_prices', 'turnover_rate',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment='换手率(%)',
               existing_nullable=True)
    op.alter_column('daily_prices', 'adj_close',
               existing_type=sa.NUMERIC(precision=19, scale=6),
               comment='后复权收盘价',
               existing_nullable=True)
    op.alter_column('daily_prices', 'adj_factor',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               comment='后复权因子',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
    op.create_unique_constraint('_security_id_date_uc', 'daily_prices', ['security_id', 'date'])
    op.create_foreign_key(None, 'daily_prices', 'securities', ['security_id'], ['id'])
    op.add_column('securities', sa.Column('em_code', sa.String(length=30), nullable=True, comment='东方财富专用代码 (如 106600519, 105.NVDA)'))
    op.alter_column('securities', 'symbol',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               comment='标准化的证券代码 (如 600519, NVDA, 00700)',
               existing_nullable=False)
    op.alter_column('securities', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment='交易所 (如 SSE, SZSE, NASDAQ, NYSE, HKEX)',
               existing_nullable=True)
    op.alter_column('securities', 'info_last_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='基本信息上次成功更新的时间',
               existing_comment='基本信息（info）上次成功更新的时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=False)
    op.create_unique_constraint('_symbol_market_type_uc', 'securities', ['symbol', 'market', 'type'])
    op.create_index(op.f('ix_securities_em_code'), 'securities', ['em_code'], unique=True)
    op.create_index(op.f('ix_securities_market'), 'securities', ['market'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_market'), table_name='securities')
    op.drop_index(op.f('ix_securities_em_code'), table_name='securities')
    op.drop_constraint('_symbol_market_type_uc', 'securities', type_='unique')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=True)
    op.alter_column('securities', 'info_last_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='基本信息（info）上次成功更新的时间',
               existing_comment='基本信息上次成功更新的时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('securities', 'exchange',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='交易所 (如 SSE, SZSE, NASDAQ, NYSE, HKEX)',
               existing_nullable=True)
    op.alter_column('securities', 'symbol',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='标准化的证券代码 (如 600519, NVDA, 00700)',
               existing_nullable=False)
    op.drop_column('securities', 'em_code')
    op.drop_constraint(None, 'daily_prices', type_='foreignkey')
    op.drop_constraint('_security_id_date_uc', 'daily_prices', type_='unique')
    op.alter_column('daily_prices', 'adj_factor',
               existing_type=sa.NUMERIC(precision=20, scale=6),
               comment=None,
               existing_comment='后复权因子',
               existing_nullable=False,
               existing_server_default=sa.text('1.0'))
    op.alter_column('daily_prices', 'adj_close',
               existing_type=sa.NUMERIC(precision=19, scale=6),
               comment=None,
               existing_comment='后复权收盘价',
               existing_nullable=True)
    op.alter_column('daily_prices', 'turnover_rate',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment=None,
               existing_comment='换手率(%)',
               existing_nullable=True)
    op.alter_column('daily_prices', 'volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='成交量（股）',
               existing_nullable=True)
    op.drop_column('daily_prices', 'avg_price')
    op.drop_column('daily_prices', 'amount')
    # ### end Alembic commands ###
