"""Add price_data_latest_date to securities table

Revision ID: 8c666c3093ce
Revises: bee40d3d4c0b
Create Date: 2025-06-25 14:04:11.478390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c666c3093ce'
down_revision: Union[str, Sequence[str], None] = 'bee40d3d4c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('price_data_latest_date', sa.Date(), nullable=True, comment='日线价格数据覆盖的最新日期'))
    op.create_index(op.f('ix_securities_price_data_latest_date'), 'securities', ['price_data_latest_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_securities_price_data_latest_date'), table_name='securities')
    op.drop_column('securities', 'price_data_latest_date')
    # ### end Alembic commands ###
