"""Update models based on recent changes

Revision ID: 8cf8bf51d248
Revises: 15ca85d367a0
Create Date: 2025-06-27 19:43:45.189746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cf8bf51d248'
down_revision: Union[str, Sequence[str], None] = '15ca85d367a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('securities', 'market',
               existing_type=postgresql.ENUM('CNA', 'HK', 'US', 'CRYPTO', 'FOREX', 'INDEX', name='market_type'),
               type_=sa.String(length=50),
               nullable=True,
               existing_comment='市场板块 (US, HK, CNA等)')
    op.alter_column('securities', 'type',
               existing_type=postgresql.ENUM('STOCK', 'ETF', 'INDEX', 'CRYPTO', 'FOREX', 'PREFERRED_STOCK', 'WARRANT', 'OTC', 'MUTUAL_FUND', name='asset_type'),
               type_=sa.String(length=50),
               nullable=True,
               existing_comment='资产类型 (STOCK, ETF等)')
    op.drop_constraint(op.f('_symbol_market_type_uc'), 'securities', type_='unique')
    op.create_unique_constraint('_symbol_market_type_uc', 'securities', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_symbol_market_type_uc', 'securities', type_='unique')
    op.create_unique_constraint(op.f('_symbol_market_type_uc'), 'securities', ['symbol', 'market', 'type'], postgresql_nulls_not_distinct=False)
    op.alter_column('securities', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('STOCK', 'ETF', 'INDEX', 'CRYPTO', 'FOREX', 'PREFERRED_STOCK', 'WARRANT', 'OTC', 'MUTUAL_FUND', name='asset_type'),
               nullable=False,
               existing_comment='资产类型 (STOCK, ETF等)')
    op.alter_column('securities', 'market',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('CNA', 'HK', 'US', 'CRYPTO', 'FOREX', 'INDEX', name='market_type'),
               nullable=False,
               existing_comment='市场板块 (US, HK, CNA等)')
    # ### end Alembic commands ###
