"""Add adj_factor to daily_prices

Revision ID: 9b057612d9dc
Revises: 7c0b05309982
Create Date: 2025-06-23 22:53:13.144923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b057612d9dc'
down_revision: Union[str, Sequence[str], None] = '7c0b05309982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('adj_factor', sa.Numeric(precision=20, scale=10), server_default='1.0', nullable=False))
    op.drop_column('daily_prices', 'adj_close_forward')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('adj_close_forward', sa.NUMERIC(precision=19, scale=4), autoincrement=False, nullable=True))
    op.drop_column('daily_prices', 'adj_factor')
    # ### end Alembic commands ###
