"""update models

Revision ID: bee40d3d4c0b
Revises: 738f9cd46830
Create Date: 2025-06-25 00:13:15.111384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee40d3d4c0b'
down_revision: Union[str, Sequence[str], None] = '738f9cd46830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('cal_event_factor', sa.Numeric(precision=20, scale=6), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_prices', 'cal_event_factor')
    # ### end Alembic commands ###
