"""update database schema

Revision ID: ccb3056986be
Revises: f6179b69232f
Create Date: 2025-06-27 00:54:53.660488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb3056986be'
down_revision: Union[str, Sequence[str], None] = 'f6179b69232f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('actions_last_updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='公司行动数据（分红/拆股）上次成功更新的时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securities', 'actions_last_updated_at')
    # ### end Alembic commands ###
