"""Update models

Revision ID: d4823e8e6b28
Revises: 8de2c0bdc8b1
Create Date: 2025-06-24 15:03:12.414060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4823e8e6b28'
down_revision: Union[str, Sequence[str], None] = '8de2c0bdc8b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('event_factor', sa.Numeric(precision=20, scale=12), nullable=False, server_default='1.0'))
    op.alter_column('daily_prices', 'event_factor', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_prices', 'event_factor')
    # ### end Alembic commands ###
