"""Update models

Revision ID: f91378dcd2a2
Revises: 037659c43fb1
Create Date: 2025-06-24 01:35:21.435322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91378dcd2a2'
down_revision: Union[str, Sequence[str], None] = '037659c43fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('adj_close', sa.Numeric(precision=19, scale=6), nullable=True))
    op.drop_column('daily_prices', 'adj_close_backward')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prices', sa.Column('adj_close_backward', sa.NUMERIC(precision=19, scale=6), autoincrement=False, nullable=True))
    op.drop_column('daily_prices', 'adj_close')
    # ### end Alembic commands ###
